name: Nightly Backup

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: {}

jobs:
  backup:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Run backup script
        env:
          BACKUP_BUCKET: ${{ secrets.BACKUP_BUCKET }}
          BACKUP_PREFIX: ${{ vars.BACKUP_PREFIX || 'portal' }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          ASSET_DIR: public/uploads
        run: |
          bash scripts/backup.sh

      - name: Upload backup summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backup-logs
          path: /tmp/portal-backup-*/
          if-no-files-found: ignore
